from django.views.generic import TemplateView, ListView

from .forms import StyleForm
from .models import Style

class StylistIndexView(ListView):
    """
    List of styles available for editing
    """
    template_name = "stylist/index.html"
    model = Style

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context["form"] = StyleForm
        return context


# Stylist Preview Link - Autogenerated CSS from SASS/SCSS


# Stylist Edit Page


# Stylist Detail Page
