from django.views.generic import TemplateView, ListView

from .models import Style

class StylistIndexView(ListView):
    """
    List of styles available for editing
    """
    # template_name = "stylist/index.html"
    model = Style


# Stylist Preview Link - Autogenerated CSS from SASS/SCSS


# Stylist Edit Page


# Stylist Detail Page
